[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.4"
once_cell = "1.9.0"
libsm = "0.6.0"
secp256k1 = { version = "0.29.0", features = ["recovery", "rand"] }
rand = "0.8.5"
sha256 = "1.5.0"
hex = "0.4.3"